### PR TITLE
Prepare next development cycle for 1.0.12

### PR DESCRIPTION
**Pull request by hs536**
Merge the 1.0.11 branch to master for next development.

### CODE REVIEW

**Comment by hs536** [comment]
This merge request fails on eclipsefdn/eca because of the glassfish-bot commits. Should I think of another way?

**Comment by arjantijms** [comment]
> This merge request fails on eclipsefdn/eca because of the glassfish-bot commits. Should I think of another way?

This remains an issue, unfortunately. Has been dragging on for a long time. Since the change is so small, perhaps it's easier to just update the version in master manually.

**Comment by hussainnm** [comment]
Even if the ECA check fails you can merge it. ECA is not applicable for bots. Merging this branch is better than creating another commit since it also contains the release tag. This branch should be deleted after merging.

**Comment by arjantijms** [comment]
@hussainnm thx!

**Pull request merged**
